{% set name = "PythonTemplate" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --force-reinstall --no-deps -vv "

requirements:
  build:
    - python
    - setuptools
  host:
    - python
  run:
    - python >=3.9

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
    - pytest-mock
  imports:
    - PythonTemplate
    

about:
  home: https://github.com/kevin931/PythonTemplate
  license: CC0
  license_family: CC0
  license_file: LICENSE.txt
  summary: CyTOF Dimension Reduction Framework.

extra:
  recipe-maintainers:
    - kevin931